# default configuration
baseURL = ""
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Kross"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"




[[menu.main]]
URL = "product"  
name = "Product"
weight = 1

hasChildren = true

 [[menu.main]]
  parent = "Product"
  name = "Sasya Smart Irrigation"
  url = "sasyasmartirrigation"
  weight = 1

  [[menu.main]]
  parent = "Product"
  name = "Greenhouse Smart Climate Control"
  url = "billing-pricing"
  weight = 2

  [[menu.main]]
  parent = "Product"
  name = "Sasya Smart Cold Storage"
  url = "features"
  weight = 3
  
  [[menu.main]]
  parent = "Product"
  name = "Bioflock Culture Management"
  url = "#"
  weight = 4
  
  [[menu.main]]
  parent = "Product"
  name = "Connected Scheduler"
  url = "features"
  weight = 5
  
[[menu.main]]
URL = "platform"
name = "Platform"
weight = 2

[[menu.main]]
URL = "gallery"  
name = "Gallery"
weight = 3

# menu
[[menu.main]]
URL = "about"
name = "About Us"
weight = 4

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = "+91 8197 239 206 | +91 9449 456 795"
email = "santosh@sasyasystems.com"
address = "426, 14th Main,23rd Cross,HSR Layout, Sector 7,Bangalore – 560102"
# meta description
author = "Johnathan Smith"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"